### PR TITLE
Fix getSerialOfFirstCamera() function when empty cameras

### PR DESCRIPTION
**Pull request by Erblinium**
Got NxLibException when having cameras with empty serial in camera list. Made the function so that it continues on to next camera instead of just returning empty serial and crashing.

### CODE REVIEW

**Comment by benthie** [comment]
Hi there and thank you very much for your PR. May I ask how you managed to get a camera with an empty serial into the camera list? Did you maybe open a file-camera and did not provide a serial?

**Comment by Erblinium** [comment]
I am a bit unsure how I have "cameras" with empty serial. I have never used file-cameras. Currently I only have one virtual camera shown in nxView, however when i run the ensenso_camera_node it finds a total of 3 cameras where the 2 first ones are empty:
image

**Comment by benthie** [comment]
Okay. That sounds a little bit awkward to me.
- Which NxLib / Ensenso SDK version are you using?
- Do you maybe have two NxLibs installed?

What you could try is the following:
- go to your Ensenso installation folder (defaults to `/opt/ensenso` on Linux, `C:\ProgramFiles\Ensenso` on Windows)
- close all running instances of `NxLib` and `NxView`
- backup your settings folder
- remove all content in your settings folder
- open `NxView` and create a new virtual camera
- open the ROS node and check that it only lists the one camera
- if you again see cameras with an empty serial, please use `NxTreeEdit` to check the content of the `itmBySerialNo` node and post it here

**Comment by Erblinium** [comment]
> Okay. That sounds a little bit awkward to me.
> 
>     * Which NxLib / Ensenso SDK version are you using?
Ubuntu 22.04 amd64 using nxLib version: 3.3.1417
>     * Do you maybe have two NxLibs installed?
How do I check that? Ran ```where nxview```, got 2 locations:  
```
/usr/bin/nxView
/bin/nxView
```
However, I see that ```/bin/nxview``` is a script that actually uses executable located in ```/opt/ensenso/bin```
> 
> What you could try is the following:
> 
>     * go to your Ensenso installation folder (defaults to `/opt/ensenso` on Linux, `C:\ProgramFiles\Ensenso` on Windows)
> 
>     * close all running instances of `NxLib` and `NxView`
> 
>     * backup your settings folder
> 
>     * remove all content in your settings folder
> 
>     * open `NxView` and create a new virtual camera
> 
>     * open the ROS node and check that it only lists the one camera
> 
>     * if you again see cameras with an empty serial, please use `NxTreeEdit` to check the content of the `itmBySerialNo` node and post it here
The NxTreeEdit when running the ROS node is all empty. Its only populated when nxView is running. I attached an nxlog file of when I ran nxview and the ROS node.

[tmp_NxTreeEdit.zip](https://github.com/ensenso/ros_driver/files/10491526/tmp_NxTreeEdit.zip)

**Pull request closed without merging**
